version: "3"

services:
  db:
    image: mariadb:10
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_PASSWORD: root
      PMA_USER: root
      PMA_HOSTS: mariadb
      PMA_PORT: 3306
    ports:
      - 8080:80
    networks:
      - db_network

volumes:
  data:

networks:
  db_network:
    driver: bridge
